---
- name: local-media-server
  hosts: localhost

  tasks:

    - name: Create docker-compose file
      no_log: True
      ansible.builtin.template:
        src: "host_files/{{ inventory_hostname }}/{{ docker_compose_template }}"
        dest: "host_files/{{ inventory_hostname }}/{{ docker_compose_file }}"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
      tags: 
        - core

    - name: Launch Containers
      community.docker.docker_compose:
        project_src: "host_files/{{ inventory_hostname }}"
        files: "{{ docker_compose_file }}"
        recreate: never
      tags:
        - core

    - name: Start Jellyfin
      ansible.builtin.command:
        cmd: open -a Jellyfin
      tags:
        - core

    - name: Remove Containers
      community.docker.docker_compose:
        project_src: "host_files/{{ inventory_hostname }}"
        files: "{{ docker_compose_file }}"
        recreate: never
        state: absent
      tags:
        - down # Remove containers

    - name: Stop Jellyfin
      ansible.builtin.command:
        cmd: osascript -e 'quit app "jellyfin"'
      tags:
        - down

