---
media_home: "{{ ansible_user_dir }}/local-media-server"
docker_compose_template: media-server-docker-compose.yml.j2
docker_compose_file: media-server-docker-compose.yml
vpn_enabled: yes
vpn_type: openvpn
vpn_username: NGtG49Je2crte2jv2HHtkQY6
vpn_password: "{{ vault_vpn_password }}"
name_servers: 8.8.8.8,4.4.4.4
lan_network: 192.168.0.0/24
webui_username: nzbget
webui_password: "{{ vault_webui_password }}"
enable_ssl: yes
timezone: Europe/Madrid
jellyfin_dmg_url: https://repo.jellyfin.org/releases/server/macos/stable/installer/Jellyfin_10.7.7.dmg
app_name: Jellyfin
